services:

  netalertx:
    image: "ghcr.io/jokob-sk/netalertx:latest"
    container_name: netalertx
#    network_mode: "host"
    volumes:
      - ./config:/app/config
      - ./db:/app/db
      - ./logs:/app/log
      - type: tmpfs
        target: /app/api
    environment:
      - TZ=America/Tijuana
#      - PORT=20211
    ports:
      - "20211:20211/tcp"
    restart: unless-stopped
